---
# Homepage configuration
# See https://fontawesome.com/v5/search for icon options

title: ""
subtitle: ""
# documentTitle: "Welcome" # Customize the browser tab text
# logo: ""
# Alternatively a fa icon can be provided:
icon: "fas fa-skull-crossbones"

header: false # Set to true/false to hide the header
footer: '<p>Copyright © All Rights Reserved</p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: light # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
 # style: "is-warning"
 # title: "Tärkeä tiedoite!"
 # icon: "fa fa-exclamation-triangle"
 # content: "Palvelussa tehdään huoltotöitä xx.xx.xxxx kello 00.00-00.00 välisenä aikana. Palvelut ovat silloin poissa käytöstä. Pahoittelen tästä aiheutuvaa haittaa."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Tukihenkilö yhteystiedot"
    target: "_blank" # optional html a tag target attribute
  - name: "Sähköposti"
    icon: "fas fa-envelope"
    url: "mailto:email@email"
  - name: "Puhelin"                                                                                                                                     
    icon: "fas fa-phone"                                                                                                                                      
    url: "tel:+3581111111" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Julkinen verkko"
    icon: "fas fa-cloud"
    items:
      - name: ""
        icon: "fab fa-internet-explorer"
        subtitle: ""
        tag: ""
        url: ""
        # Optional tagstyle
        tagstyle: "is-success"
      - name: ""
        icon: "fas fa-hdd" 
        subtitle: ""
        tag: ""
        url: ""
        # Optional tagstyle                                                                                                                                                                                       
        tagstyle: "is-success"
  - name: "Suljettu verkko"                                                                                                                                                                                      
        
    icon: "fas fa-ethernet"                                                                                                                                                                                          
    items:                                                                                                                                                                                                                                                                                                                                                                                           
      - name: ""                                                                                                                                                                                       
        icon: "fas fa-file"                                                                                                                                                                           
        subtitle: ""                                                                                                                                                                
        tag: ""                                                                                                                                                                                                
        url: "" 
      - name: ""                                                                                                                                                                                       
        icon: "fas fa-user"                                                                                                                                                                           
        subtitle: ""                                                                                                                                                                    
        tag: ""                                                                                                                                                                                                
        url: ""
      - name: ""                                                                                                                                                                                       
        icon: "fas fa-key" 
        subtitle: ""                                                                                                                                                                    
        tag: ""                                                                                                                                                                                                
        url: ""
      - name: ""                                                                                                                                                                                       
        icon: "fas fa-video"                                                                                                                                                                          
        subtitle: ""                                                                                                                                                                    
        tag: ""                                                                                                                                                                                                
        url: ""
      - name: ""
        icon: "fas fa-lock"
        subtitle: ""
        tag: ""
        url: ""
      - name: ""
        icon: "fas fa-lock"
        subtitle: ""
        tag: ""
        url: ""       
   
                                                                                                                          
                                                                                                                                                                                          

                                                                                                                                                                                         
                                                                                                                                                                     
                                                              
